### ISSUE TITLE
Links to vignettes are broken.

### ISSUE THREAD

**Issue by Kevin-M-Smith** [mccreigh/rwrfhydro#31]
See https://github.com/mccreigh/rwrfhydro/blob/master/vignettes.Rmd which is currently in this state: https://github.com/mccreigh/rwrfhydro/blob/3cca055bf444581d503adeb2eaa94fddd0985a63/vignettes.Rmd

**Comment by mccreigh** [comment]
Hi Kevin!
Thanks for filing the very first issue!
Yes, the v3 code release has been delayed and the vignettes homepage with it. I've staged the vignettes here https://goo.gl/jK5NXX and I'll also put the test case there shortly. These links may only be temporary and hopefully the links you referred to will be operational in the near future. 
Please follow up if that does not resolve the issue. 
Thanks, 
James

**Comment by Kevin-M-Smith** [comment]
Excellent, thanks!
