### ISSUE TITLE
rwrfhydro install errors 

### ISSUE THREAD

**Issue by lread1** [mccreigh/rwrfhydro#39]
I receive the following error when I attempt to execute the command: devtools::install_github("mccreigh/rwrfhydro")

ERROR: dependencies 'ncdf4', 'doMC' are not available for package 'rwrfhydro'

I successfully installed devtools. 

Thanks,
Laura

**Comment by mccreigh** [comment]
Hi Laura-

I need to know some basic things about your system and R to have any clue. Please send the output of the R command `sessionInfo()`. It will look like this: 

```
R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.4 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
```

Primarily this will tell me if you're on windows but there may be other clues. 

You may also want to refer to the "cutting-edge" README, which is in devBranch,  here:
https://github.com/mccreigh/rwrfhydro/blob/devBranch/README.Rmd

If you are on windows, then this version of the README should help you install ncdf4 See the bottom of this section: https://github.com/mccreigh/rwrfhydro/blob/devBranch/README.Rmd#installing

doMC is not available on windows. 

If you get ncdf4 installed (via the above), then the devBranch should install (I believe we changed the dependencies on doMC). Try this:

```
devtools::install_github("mccreigh/rwrfhydro", ref='devBranch')
```

James

**Comment by lread1** [comment]
Hi James,

I am on Windows.  I followed the steps you suggested and it worked!

Thanks,
Laura
