### ISSUE TITLE
wrfHydroTestCases

### ISSUE THREAD

**Issue by BeatrizRR** [mccreigh/rwrfhydro#41]
Hi all,

Apologised for this very basic question...but where can I get the wrfHydroTestCases data folder?
(Couldn't find out anywhere)

Thanks!

Beatriz

**Comment by mccreigh** [comment]
Hi Beatriz-
Sorry, we'll eventually try to make this more clear. 

goo.gl/9PM9aW

expands to 

https://c6e6fa24700ba70c9c83500c1900bd5355b2f010-www.googledrive.com/host/0B2KdnjgYjCsLTWdRV2x0dzd0RDA/

Let us know if you arent finding what you need. 
James

**Comment by BeatrizRR** [comment]
Thank you this! found it,

Beatriz

**Comment by BeatrizRR** [comment]
Hi, me again.

Would be possible to also access "'~/wrfHydroTestCases/usgsDb/'" dataset? I couldn't found it within the Fourmile_Creek data.

Thanks James.

Bea

**Comment by jmccreight** [comment]
Hi Beatriz-

Thanks for making this an issue. I've known about it for a while, but it
fell off my radar.

I wont be able to fix this properly until next week. However, I believe
that if you run this vignette first
*4. Collect USGS stream observations and build a local database.
<http://www.googledrive.com/host/0B2KdnjgYjCsLbng2Q1hOa1BINXc>*
it will solve the problem.

Best,
James



-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by BeatrizRR** [comment]
Hi James,
Thanks for your quick reply. In fact I "delete" my question because I decide to properly start from Vignette 1, and right now I'm on 4 and discovered I can make the database myself. :) Enjoying going through them! Very useful!

Regards,

Bea

**Comment by jmccreight** [comment]
glad it works. and more glad you are enjoying it.!
please leave the issue open, I should fix this...


-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149
