### ISSUE TITLE
Help pinpoint a installation failure cause?

### ISSUE THREAD

**Issue by muratetm** [mccreigh/rwrfhydro#46]
I tried the install via devtools and get the following:

> devtools::install_github("mccreigh/rwrfhydro")
Downloading github repo mccreigh/rwrfhydro@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command

Here is the Sys.info
> Sys.info()
                                       sysname 
                                       "Linux" 
                                       release 
                           "3.13.0-79-generic" 
                                       version 
"#123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016" 
                                      nodename 
                                      "fisher" 
                                       machine 
                                      "x86_64" 
                                         login 
                                    "mmuratet" 
                                          user 
                                    "mmuratet" 
                                effective_user 
                                    "mmuratet" 

I tried to increase the information, but to no avail

> devtools::install_github("mccreigh/rwrfhydro",quiet=FALSE)
Downloading github repo mccreigh/rwrfhydro@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command

Can you suggest a way to determine what it is unhappy about?

Thanks

Mike

**Comment by jmccreight** [comment]
what machine are you on?


-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by muratetm** [comment]
A Dell workstation 

ubuntu 14.40 LTS
Intel Xeon(R) E5-2630v3 2.4GHz x 16
32Gb memory
Gallium 0.4 on NVD9 graphics card

I was able to download the zip of the directory tree from github with the ‘download zip’ button, but I can’t get the devtools install to work

Thanks

Mike

**Comment by jmccreight** [comment]
are you in the lab downstairs? which computer specifically. I can log in to
it



-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by jmccreight** [comment]
But maybe you're not down there becase rwrfhydro should already be
installed.
if so just
library(rwrfhydro)

regardless, I'd ask you to
devtools::install_github("mccreigh/rwrfhydro", ref='devBranch')


-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by muratetm** [comment]
I’m in Huntsville, AL. Have I inadvertently reached some forbidden place?

**Comment by muratetm** [comment]
I’ve been trying to run the scripts in the R folder and I’m getting complaints about no curl. It is installed, but that might be why the rwrfhydro won’t install

**Comment by jmccreight** [comment]
Sorry. We have a class going on right now, I assumed you were in there.

send me the output of
sessionInfo()

Try this and see if the failure is more informative/different
devtools::install_github("mccreigh/rwrfhydro", ref='devBranch')


-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by muratetm** [comment]
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
  [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods base

other attached packages:
[1] curl_0.5

loaded via a namespace (and not attached):
[1] codetools_0.2-10 foreach_1.4.2    iterators_1.0.7 plyr_1.8.1
[5] Rcpp_0.11.5      tools_3.1.3

I did get curl to install.

 > devtools::install_github("mccreigh/rwrfhydro",ref='devBranch')
Downloading github repo mccreigh/rwrfhydro@devBranch
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) :
   error in running command


Thanks

Mike

**Comment by jmccreight** [comment]
this is not like I've ever seen...

try this
library(devtools)
sessionInfo()
install_github("mccreigh/rwrfhydro",ref='devBranch')

-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149

**Comment by muratetm** [comment]
> library(devtools)
 > sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu 14.04.4 LTS

locale:
  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
  [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods base

other attached packages:
[1] devtools_1.7.0 curl_0.5

loaded via a namespace (and not attached):
  [1] bitops_1.0-6     codetools_0.2-10 foreach_1.4.2 httr_0.6.1
  [5] iterators_1.0.7  plyr_1.8.1       Rcpp_0.11.5 RCurl_1.95-4.5
  [9] stringr_0.6.2    tools_3.1.3
 > install_github("mccreigh/rwrfhydro",ref='devBranch')
Downloading github repo mccreigh/rwrfhydro@devBranch
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) :
   error in running command

It is weird, but I have the scripts I need working (snodas). I thought 
there might be a simple explanation that an experienced user would know, 
but I don't want to take up your time.

Mike

**Comment by muratetm** [comment]
That was it.

It would have taken me a long time to find that, thanks.

I have to update my R to 3.2.0, but I know how to do that.

Cheers

Mike

**Comment by jmccreight** [comment]
I just googled
"devtools error in running command"


good luck out there!!
btw new release coming soon (not that it really matters if you're using
devBranch).

James



-------------------------------------------------------
James L. McCreight
office: (303) 497-8404
cell:     (831) 261-5149
